export default {
  get: jest.fn().mockResolvedValue({
    data: {
      products: [
        {
          id: "MLA1363245591",
          title: "Apple AirPods Pro - Blanco",
          price: { amount: "36299", currency: "ARS", decimals: 0 },
          installments: { amount: "8974.93", quantity: 6 },
          address: { city_name: "San Justo", state_name: "Buenos Aires" },
          condition: "new",
          free_shipping: true,
          picture:
            "http://http2.mlstatic.com/D_675358-MLA46180781012_052021-I.jpg",
        },
        {
          id: "MLA1361987405",
          title: "Cargador Apple Base Dock Lightning",
          price: { amount: "20399", currency: "ARS", decimals: 0 },
          installments: { amount: "6799.67", quantity: 3 },
          address: { city_name: "Villa Martelli", state_name: "Buenos Aires" },
          condition: "new",
          free_shipping: true,
          picture:
            "http://http2.mlstatic.com/D_814321-MLA27822471143_072018-I.jpg",
        },
        {
          id: "MLA1131886168",
          title: "Apple Earpods Con Conector De 3.5 Mm - Blanco",
          price: { amount: "8459", currency: "ARS", decimals: 6 },
          installments: { amount: "2091.5", quantity: 6 },
          address: { city_name: "Floresta", state_name: "Capital Federal" },
          condition: "new",
          free_shipping: true,
          picture:
            "http://http2.mlstatic.com/D_831247-MLA46346545723_062021-I.jpg",
        },
        {
          id: "MLA1292496774",
          title:
            "Cable iPad 1 2 3 De 30 Pines A Usb En Caja Sellada Original - iPad / iPhone / iPod / Local --",
          price: { amount: "1390", currency: "ARS", decimals: 0 },
          installments: { amount: "231.67", quantity: 6 },
          address: { city_name: "Pilar", state_name: "Buenos Aires" },
          condition: "new",
          free_shipping: false,
          picture:
            "http://http2.mlstatic.com/D_928297-MLA52233965441_112022-I.jpg",
        },
        {
          id: "MLA812447160",
          title: "Film Tricapa iPod Nano Touch 6 Generacion Combo 5 Unidades",
          price: { amount: "711", currency: "ARS", decimals: 56 },
          installments: { amount: "175.93", quantity: 6 },
          address: { city_name: "San Nicolás", state_name: "Capital Federal" },
          condition: "new",
          free_shipping: false,
          picture:
            "http://http2.mlstatic.com/D_4192-MLA2776758135_062012-I.jpg",
        },
        {
          id: "MLA810350827",
          title:
            "Auriculares Sony Over-ear Best Stereo Extra Bass Portatil Plegable Headset Para Apple iPhone iPod/samsung Galaxy/mp3 Pla",
          price: { amount: "25289", currency: "ARS", decimals: 0 },
          installments: { amount: "6252.71", quantity: 6 },
          address: { city_name: "Quilmes", state_name: "Buenos Aires" },
          condition: "new",
          free_shipping: true,
          picture:
            "http://http2.mlstatic.com/D_779278-MLA31900758753_082019-I.jpg",
        },
        {
          id: "MLA1378313514",
          title:
            "Cable 2 Metros Usb Original Apple ® iPhone 5 6 6s 7 8 X Plus Xr Xs Max",
          price: { amount: "2185", currency: "ARS", decimals: 0 },
          installments: { amount: "540.24", quantity: 6 },
          address: { city_name: "Córdoba", state_name: "Córdoba" },
          condition: "new",
          free_shipping: false,
          picture:
            "http://http2.mlstatic.com/D_760164-MLA31024995585_062019-I.jpg",
        },
        {
          id: "MLA1292454180",
          title: "Parlante Potente Onbeat Jbl Dock iPod iPad Apple Nuevo Ns",
          price: { amount: "11499", currency: "ARS", decimals: 0 },
          installments: { amount: "1916.5", quantity: 6 },
          address: {
            city_name: "Villa Ortúzar",
            state_name: "Capital Federal",
          },
          condition: "new",
          free_shipping: true,
          picture:
            "http://http2.mlstatic.com/D_985063-MLA53070964816_122022-I.jpg",
        },
        {
          id: "MLA810400142",
          title:
            "Auriculares Sony Over-ear Best Stereo Extra Bass Portatil Headset Para Apple iPhone iPod/samsung Galaxy / Mp3 Player / 3",
          price: { amount: "28879", currency: "ARS", decimals: 0 },
          installments: { amount: "7140.33", quantity: 6 },
          address: { city_name: "Quilmes", state_name: "Buenos Aires" },
          condition: "new",
          free_shipping: true,
          picture:
            "http://http2.mlstatic.com/D_653557-MLA31904716173_082019-I.jpg",
        },
        {
          id: "MLA1372023134",
          title: "Apple Adaptador Hdmi Para iPhone/iPad/iPod Lightning",
          price: { amount: "34999", currency: "ARS", decimals: 0 },
          installments: { amount: "8653.5", quantity: 6 },
          address: { city_name: "Montserrat", state_name: "Capital Federal" },
          condition: "new",
          free_shipping: true,
          picture:
            "http://http2.mlstatic.com/D_754299-MLA31080560195_062019-I.jpg",
        },
      ],
      available_sorts: [
        { id: "price_asc", name: "Menor precio" },
        { id: "price_desc", name: "Mayor precio" },
      ],
      available_filters: [
        {
          id: "discount",
          name: "Descuentos",
          type: "number",
          values: [
            { id: "5-100", name: "Desde 5% OFF", results: 14 },
            { id: "10-100", name: "Desde 10% OFF", results: 9 },
          ],
        },
        {
          id: "category",
          name: "Categorías",
          type: "text",
          values: [
            { id: "MLA409810", name: "Audio", results: 262 },
            { id: "MLA1648", name: "Computación", results: 14 },
            { id: "MLA3502", name: "Accesorios para Celulares", results: 97 },
            { id: "MLA3813", name: "Repuestos de Celulares", results: 11 },
            { id: "MLA4641", name: "Pilas y Cargadores", results: 8 },
            { id: "MLA1055", name: "Celulares y Smartphones", results: 6 },
            { id: "MLA58775", name: "Fundas y Bolsos", results: 6 },
            { id: "MLA4632", name: "Controles Remotos", results: 3 },
            {
              id: "MLA3690",
              name: "Accesorios para Audio y Video",
              results: 2,
            },
            { id: "MLA5054", name: "Cables", results: 2 },
            { id: "MLA11830", name: "Componentes Electrónicos", results: 2 },
            { id: "MLA1039", name: "Cámaras y Accesorios", results: 2 },
            { id: "MLA5725", name: "Accesorios para Vehículos", results: 1 },
            { id: "MLA1367", name: "Antigüedades y Colecciones", results: 1 },
            { id: "MLA1276", name: "Deportes y Fitness", results: 1 },
            { id: "MLA1499", name: "Industrias y Oficinas", results: 1 },
            { id: "MLA417704", name: "Smartwatches y Accesorios", results: 1 },
            { id: "MLA1915", name: "Otros", results: 3 },
            { id: "MLA1953", name: "Otras categorías", results: 1 },
          ],
        },
        {
          id: "price",
          name: "Precio",
          type: "range",
          values: [
            { id: "*-5500.0", name: "Hasta $ 5.500", results: 140 },
            { id: "5500.0-15000.0", name: "$5.500 a $15.000", results: 123 },
            { id: "15000.0-*", name: "Más de $15.000", results: 159 },
          ],
        },
        {
          id: "accepts_mercadopago",
          name: "Filtro por MercadoPago",
          type: "boolean",
          values: [{ id: "yes", name: "Con MercadoPago", results: 422 }],
        },
        {
          id: "installments",
          name: "Pago",
          type: "text",
          values: [
            { id: "yes", name: "En cuotas", results: 422 },
            { id: "no_interest", name: "Sin interés", results: 27 },
          ],
        },
        {
          id: "shipping",
          name: "Tipo de entrega",
          type: "text",
          values: [
            { id: "mercadoenvios", name: "Con envío", results: 413 },
            { id: "fulfillment", name: "Full", results: 1 },
          ],
        },
        {
          id: "power_seller",
          name: "Filtro por calidad de vendedores",
          type: "boolean",
          values: [{ id: "yes", name: "Mejores vendedores", results: 106 }],
        },
        {
          id: "since",
          name: "Filtro por fecha de comienzo",
          type: "text",
          values: [{ id: "today", name: "Publicados hoy", results: 2 }],
        },
        {
          id: "until",
          name: "Filtro por fecha de finalización",
          type: "text",
          values: [{ id: "today", name: "Finalizan hoy", results: 2 }],
        },
        {
          id: "has_video",
          name: "Filtro por publicaciones con video",
          type: "boolean",
          values: [{ id: "yes", name: "Publicaciones con video", results: 8 }],
        },
        {
          id: "has_pictures",
          name: "Filtro por publicaciones con imágenes",
          type: "boolean",
          values: [{ id: "yes", name: "Con fotos", results: 422 }],
        },
        {
          id: "all_payment_methods_discount",
          name: "Descuentos para todos los medios de pago",
          type: "number",
          values: [{ id: "10-100", name: "Desde 10% OFF", results: 9 }],
        },
        {
          id: "price_campaign_id",
          name: "Campaña",
          type: "number",
          values: [
            { id: "P-MLA10757004", name: "P-MLA10757004", results: 8 },
            { id: "MLA29722", name: "MLA29722", results: 3 },
            { id: "P-MLA10761008", name: "P-MLA10761008", results: 1 },
          ],
        },
        {
          id: "shipping_cost",
          name: "Costo de envío",
          type: "text",
          values: [{ id: "free", name: "Gratis", results: 110 }],
        },
        {
          id: "BRAND",
          name: "Marca",
          type: "STRING",
          values: [
            { id: "9344", name: "Apple", results: 332 },
            { id: "276243", name: "Genérica", results: 23 },
            { id: "44193", name: "iHome", results: 3 },
            { id: "11452545", name: "Ulak", results: 3 },
            { id: "995", name: "Sony", results: 2 },
            { id: "2964515", name: "Mobile Edge", results: 2 },
            { id: "149762", name: "Cameron Sino", results: 2 },
            { id: "11100246", name: "OtterBox", results: 2 },
            { id: "3204797", name: "Maximal Power", results: 1 },
            { id: "2946558", name: "Mili", results: 1 },
            { id: "2785885", name: "iPad", results: 1 },
            { id: "2503", name: "Motorola", results: 1 },
            { id: "2318991", name: "Desigual", results: 1 },
            { id: "19922", name: "Built", results: 1 },
            { id: "17265", name: "JBL", results: 1 },
            { id: "1113571", name: "Mobo", results: 1 },
            { id: "1025369", name: "TGW", results: 1 },
          ],
        },
        {
          id: "ITEM_CONDITION",
          name: "Condición",
          type: "STRING",
          values: [
            { id: "2230581", name: "Usado", results: 284 },
            { id: "2230284", name: "Nuevo", results: 138 },
          ],
        },
        {
          id: "state",
          name: "Ubicación",
          type: "text",
          values: [
            { id: "TUxBUENBUGw3M2E1", name: "Capital Federal", results: 233 },
            {
              id: "TUxBUEdSQWU4ZDkz",
              name: "Bs.As. G.B.A. Norte",
              results: 61,
            },
            { id: "TUxBUEdSQXJlMDNm", name: "Bs.As. G.B.A. Sur", results: 53 },
            {
              id: "TUxBUEdSQWVmNTVm",
              name: "Bs.As. G.B.A. Oeste",
              results: 16,
            },
            { id: "TUxBUENPUmFkZGIw", name: "Córdoba", results: 13 },
            { id: "TUxBUFNBTmU5Nzk2", name: "Santa Fe", results: 12 },
            {
              id: "TUxBUENPU2ExMmFkMw",
              name: "Bs.As. Costa Atlántica",
              results: 5,
            },
            { id: "TUxBUE1FTmE5OWQ4", name: "Mendoza", results: 4 },
            {
              id: "TUxBUFpPTmFpbnRl",
              name: "Buenos Aires Interior",
              results: 4,
            },
            { id: "TUxBUFNBTGFjMTJi", name: "Salta", results: 3 },
            { id: "TUxBUE5FVW4xMzMzNQ", name: "Neuquén", results: 2 },
            { id: "TUxBUEVOVHMzNTdm", name: "Entre Ríos", results: 2 },
            { id: "TUxBUEpVSnk3YmUz", name: "Jujuy", results: 2 },
            { id: "TUxBUFRVQ244NmM3", name: "Tucumán", results: 2 },
            { id: "TUxBUFLNT29iZmZm", name: "Río Negro", results: 1 },
            { id: "TUxBUFNBTm5lYjU4", name: "San Juan", results: 1 },
            { id: "TUxBUFNBTnM0ZTcz", name: "San Luis", results: 1 },
          ],
        },
        {
          id: "product",
          name: "Producto",
          type: "text",
          values: [
            { id: "MLA20004340", name: "Apple 30 pin USB", results: 5 },
            { id: "MLA8051722", name: "Cargador Apple MD836", results: 4 },
            {
              id: "MLA7931059",
              name: "Cargador Apple A1385 de pared",
              results: 3,
            },
            {
              id: "MLA10110844",
              name: "Cargador Apple Base Dock Lightning",
              results: 2,
            },
            {
              id: "MLA15306524",
              name: "Apple AirPods Pro MWP22AM",
              results: 2,
            },
            {
              id: "MLA15542338",
              name: "Apple EarPods with 3.5 mm Connector A1472",
              results: 2,
            },
            { id: "MLA19732389", name: "Apple Silicone case", results: 2 },
            {
              id: "MLA20004423",
              name: "Cable iPad 1 2 3 De 30 Pines A Usb En Caja Sellada Original - iPad / iPhone / iPod / Local --",
              results: 2,
            },
            { id: "MLA20536474", name: "Apple USB Lightning USB", results: 2 },
            { id: "MLA9316592", name: "Cargador Apple MD811X/A", results: 2 },
            { id: "MLA10515518", name: "Apple iTunes", results: 1 },
            {
              id: "MLA15306525",
              name: "Apple AirPods Pro - Blanco",
              results: 1,
            },
            {
              id: "MLA15542339",
              name: "Apple EarPods con conector de 3.5 mm - Blanco",
              results: 1,
            },
            {
              id: "MLA19732393",
              name: "Funda silicone cover Apple Silicone case surf blue con diseño liso para Apple iPhone 11 por 1 unidad",
              results: 1,
            },
            {
              id: "MLA20536482",
              name: "Cable 2 Metros Usb Original Apple ® iPhone 5 6 6s 7 8 X Plus Xr Xs Max",
              results: 1,
            },
            {
              id: "MLA22209767",
              name: "Apple Digital AV Adapter HDMI Lightning",
              results: 1,
            },
            {
              id: "MLA22209792",
              name: "Apple Adaptador Hdmi Para iPhone/iPad/iPod Lightning",
              results: 1,
            },
            { id: "MLA7948492", name: "Apple MD810E/A USB", results: 1 },
            { id: "MLA8051727", name: "Cargador Apple A1401", results: 1 },
            { id: "MLA10522577", name: "Genérica MP3", results: 1 },
            { id: "MLA10756255", name: "Underwater Audio Shuffle", results: 1 },
            {
              id: "MLA13692347",
              name: "Apple MagSafe MacBook 85 W",
              results: 1,
            },
            { id: "MLA5513986", name: "Apple iPhone 5s", results: 1 },
            { id: "MLA6007095", name: "Apple iPhone", results: 1 },
            { id: "MLA6107182", name: "Apple Tapa trasera", results: 1 },
            { id: "MLA8051721", name: "Cargador Apple A1400", results: 1 },
            { id: "MLA8752450", name: "Apple iPhone 8 Plus", results: 1 },
            { id: "MLA9217896", name: "Cargador Apple A1070", results: 1 },
          ],
        },
      ],
      query: {
        search: "Apple Ipod",
        sort: { id: "relevance", name: "Más relevantes" },
        price: "*-*",
      },
    },
  }),
};
